### ISSUE TITLE
Improved Magazine support

### ISSUE THREAD

**Issue by Harnish** [openam/calibrephp#11]
Magazines should to also sort based on the month in the series view.  

Thanks

**Comment by openam** [comment]
I'm not sure what exactly you are proposing. Could you please clarify what you want?

I don't think Calibre has built in magazine support. It sounds like you are using the series field to group magazines together. People are probably organizing magazines different ways.

There is a "published" field that has month and year. There's also a "date" field that has month, day and year. I know there are some magazines that are published multiple times a month, so I don't know how the "published" field would work.
