### ISSUE TITLE
New Installation: Missing Database Table

### ISSUE THREAD

**Issue by kinshuksunil** [openam/calibrephp#15]
Missing Database Table
Error: Table settings for model Setting was not found in datasource database.

Notice: If you want to customize this error message, create app/View/Errors/missing_table.ctp

STACK TRACE

CORE/Cake/Model/Model.php line 3243 → Model->setSource(string)
CORE/Cake/Model/Model.php line 2696 → Model->getDataSource()
APP/Model/Setting.php line 70 → Model->find(string, array)
APP/Controller/AppController.php line 68 → Setting->load()
[internal function] → AppController->beforeFilter(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 248 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 670 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 184 → Controller->startupProcess()
CORE/Cake/Routing/Dispatcher.php line 162 → Dispatcher->_invoke(BooksController, CakeRequest, CakeResponse)
APP/webroot/index.php line 109 → Dispatcher->dispatch(CakeRequest, CakeResponse)
ROOT/index.php line 43 → require(string)

**Comment by openam** [comment]
@kinshuksunil how are you trying to start the app? Are you using docker, or just running on a php installation? Did you go through the installation steps, http://openam.github.io/calibrephp/#installation?

**Comment by kinshuksunil** [comment]
I copied the files to the directory. Did not use the Docker approach.
Edited the database.php, core.php and settings.php

Now when I launch the app by visiting the URL, I face this error.

**Comment by hjbarraza** [comment]
@kinshuksunil Did you manage to fix it?

**Comment by openam** [comment]
@kinshuksunil can change the `database.php` back to what it originally was, and then just go to the settings (user dropdown) and set the path for where your `metadata.db` file is, e.g. `/Users/michael/Documents/Calibre Library/metadata.db`

**Comment by openam** [comment]
@kinshuksunil @hjbarraza I've made a couple small updates, and updated the documentation site.

**Comment by kinshuksunil** [comment]
I will try these out and update. I had stopped using the tool.

**Comment by kinshuksunil** [comment]
Fixed. Sorry for the late reply.

**Comment by hjbarraza** [comment]
Thanks will try again this weeekend.
