### ISSUE TITLE
as change the English to Spanish language?

### ISSUE THREAD

**Issue by LibreriaDigitalAmalibaka** [openam/calibrephp#4]
Template in which I can change the language?

![cambiar](https://f.cloud.github.com/assets/6087362/1893061/0d8d192e-7a69-11e3-83ed-d64c03e3269d.png)

Thanks!!

**Comment by openam** [comment]
@LibreriaDigitalAmalibaka there was support added for Russian, https://github.com/openam/calibrephp/commit/efc97f506b185fffe25905d9316f664a47fde9b7. You may be able to do the same thing.
